<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    <Authors>Rares Zamfiriu</Authors>
    <Copyright>Copyright © 2026 Rares Zamfiriu</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/rzamfiriu/webviewdriver</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <RepositoryUrl>https://github.com/rzamfiriu/webviewdriver.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <VersionPrefix>0.3.0</VersionPrefix>
  </PropertyGroup>

  <!-- Packaging (applies to packable library projects). -->
  <PropertyGroup>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
</Project>
